In [9]:
import pandas as pd

In [10]:
##Reading data

In [11]:
df = pd.read_csv('data.csv')

In [12]:
df.head()

fever  bodyPain  age  runnyNose  difficultyBreath  infectionProb
0  100.985915         0   95          1                -1              0
1   98.967264         1   25          1                 1              0
2   98.116228         0   59          1                -1              0
3  100.767500         0   60          1                 1              0
4  100.190509         0   43          1                 1              0

In [13]:
df['fever'].datacount()

AttributeError: 'Series' object has no attribute 'datacount'

In [14]:
df['fever'].value_counts()

100.495264    1
99.987871     1
99.750537     1
101.872488    1
99.006966     1
             ..
98.346673     1
100.573172    1
98.179445     1
100.163511    1
100.675035    1
Name: fever, Length: 999, dtype: int64

In [15]:
import numpy as np

In [16]:
def split_data(data,ratio):
    shuffled=np.random.permutation(len(data))
    test_data_set=int(len(data)*ratio)
    test_indices=shuffled[:test_data_set]
    train_indices=shuffled[test_data_set:]
    return data.iloc[test_indices],data.iloc[train_indices]

In [17]:
train,test = split_data(df,0.2)

In [18]:
print(train)

          fever  bodyPain  age  runnyNose  difficultyBreath  infectionProb
744  101.206373         0   55          0                 0              0
879  101.642209         0   98          0                 1              1
151  100.591920         0   88          1                 0              0
767   98.557991         0   86          0                -1              0
995  100.696133         0   33          1                -1              0
..          ...       ...  ...        ...               ...            ...
180  101.214610         0   69          1                 0              1
243   99.260592         1   32          1                 1              1
69   100.875326         0  100          0                -1              1
24   100.285956         0   73          1                 0              0
341   99.126343         1   90          0                -1              0

[199 rows x 6 columns]


In [19]:
print(test)

          fever  bodyPain  age  runnyNose  difficultyBreath  infectionProb
91    98.545637         0   83          1                -1              1
71    98.071690         1   37          0                 0              0
448   99.746696         1   97          1                -1              0
771  101.771290         1   24          0                -1              0
360  101.689466         1   68          0                 0              0
..          ...       ...  ...        ...               ...            ...
546  100.734649         1   62          1                 1              0
161   99.680160         0   35          1                -1              1
240  100.600878         1   73          1                 1              0
113   98.453673         1   69          1                 0              1
457  101.480713         0   62          0                 1              1

[800 rows x 6 columns]


In [20]:
X_train=train[['fever','bodyPain','age','runnyNose','difficultyBreath']]

In [21]:
X_train

fever  bodyPain  age  runnyNose  difficultyBreath
744  101.206373         0   55          0                 0
879  101.642209         0   98          0                 1
151  100.591920         0   88          1                 0
767   98.557991         0   86          0                -1
995  100.696133         0   33          1                -1
..          ...       ...  ...        ...               ...
180  101.214610         0   69          1                 0
243   99.260592         1   32          1                 1
69   100.875326         0  100          0                -1
24   100.285956         0   73          1                 0
341   99.126343         1   90          0                -1

[199 rows x 5 columns]

In [38]:
X_train=train[['fever','bodyPain','age','runnyNose','difficultyBreath']].to_numpy()

In [39]:
X_train=train[['fever','bodyPain','age','runnyNose','difficultyBreath']].to_numpy()

In [37]:
X_train


array([[101.2063726 ,   0.        ,  55.        ,   0.        ,
          0.        ],
       [101.642209  ,   0.        ,  98.        ,   0.        ,
          1.        ],
       [100.5919197 ,   0.        ,  88.        ,   1.        ,
          0.        ],
       [ 98.55799065,   0.        ,  86.        ,   0.        ,
         -1.        ],
       [100.6961329 ,   0.        ,  33.        ,   1.        ,
         -1.        ],
       [ 98.68846655,   1.        ,  77.        ,   1.        ,
          0.        ],
       [ 98.08961727,   1.        ,  97.        ,   1.        ,
          1.        ],
       [100.6025197 ,   1.        ,  56.        ,   0.        ,
         -1.        ],
       [100.4880029 ,   0.        ,  88.        ,   1.        ,
         -1.        ],
       [ 98.99909677,   1.        ,  60.        ,   0.        ,
          0.        ],
       [ 98.44472297,   0.        ,  93.        ,   1.        ,
          0.        ],
       [100.675035  ,   0.        ,  90.   

In [54]:
X_test=test[['fever','bodyPain','age','runnyNose','difficultyBreath']].to_numpy()

In [55]:
X_test

array([[ 98.54563675,   0.        ,  83.        ,   1.        ,
         -1.        ],
       [ 98.07168965,   1.        ,  37.        ,   0.        ,
          0.        ],
       [ 99.74669551,   1.        ,  97.        ,   1.        ,
         -1.        ],
       ...,
       [100.6008781 ,   1.        ,  73.        ,   1.        ,
          1.        ],
       [ 98.45367319,   1.        ,  69.        ,   1.        ,
          0.        ],
       [101.4807132 ,   0.        ,  62.        ,   0.        ,
          1.        ]])

In [50]:
Y_train=train['infectionProb'].to_numpy().reshape(199,)

In [51]:
Y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0])

In [56]:
Y_test=test['infectionProb'].to_numpy().reshape(800,)

In [57]:
Y_test

array([1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,

In [58]:
from sklearn.linear_model import LogisticRegression

In [59]:
clf = LogisticRegression()

In [60]:
clf.fit(X_train,Y_train)

LogisticRegression()

In [69]:
inf_prob=clf.predict_proba([[100,1,23,1,-1]])[0][1]

In [70]:
print(inf_prob)

0.36268652929062173


In [68]:
print(inf_prob[0][1])

0.36268652929062173
